#pragma once


#ifdef AUDIO_ENABLE
	#define STARTUP_SONG SONG(ZELDA_TREASURE)
	#define AUDIO_CLICKY
#endif

#define TAPPING_TERM 200
// #define PERMISSIVE_HOLD
#define IGNORE_MOD_TAP_INTERRUPT
// #define RETRO_TAPPING

